-- ============================================================
-- Migration: 20260520 — Beta schema additions
-- Run in the Supabase SQL editor.
-- Fully additive — does not drop or modify existing columns.
-- ============================================================


-- ============================================================
-- 0. Shared updated_at trigger function
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


-- ============================================================
-- 1. schedule_items — add missing beta columns
-- ============================================================
-- Existing columns kept as-is:
--   id, child_id, time (TEXT), title, type, done, active, notes,
--   scheduled_date, created_at
-- New columns are all nullable so existing rows are unaffected.

ALTER TABLE schedule_items
  ADD COLUMN IF NOT EXISTS household_id         UUID        REFERENCES households(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS description          TEXT,
  ADD COLUMN IF NOT EXISTS activity_type        TEXT,
  ADD COLUMN IF NOT EXISTS start_time           TIME,
  ADD COLUMN IF NOT EXISTS end_time             TIME,
  ADD COLUMN IF NOT EXISTS flexible_window_label TEXT,
  ADD COLUMN IF NOT EXISTS status               TEXT        CHECK (status IN ('planned','completed','skipped','replaced')) DEFAULT 'planned',
  ADD COLUMN IF NOT EXISTS created_by           TEXT,
  ADD COLUMN IF NOT EXISTS completed_by         TEXT,
  ADD COLUMN IF NOT EXISTS updated_at           TIMESTAMPTZ DEFAULT NOW();

-- Back-fill status from the legacy done boolean for existing rows
UPDATE schedule_items
  SET status = CASE WHEN done = TRUE THEN 'completed' ELSE 'planned' END
  WHERE status IS NULL;

-- Back-fill household_id from the child's household for existing rows
UPDATE schedule_items si
  SET household_id = c.household_id
  FROM children c
  WHERE si.child_id = c.id
    AND si.household_id IS NULL;

CREATE OR REPLACE TRIGGER set_schedule_items_updated_at
  BEFORE UPDATE ON schedule_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_schedule_items_child_date
  ON schedule_items (child_id, scheduled_date);

CREATE INDEX IF NOT EXISTS idx_schedule_items_household
  ON schedule_items (household_id);

CREATE INDEX IF NOT EXISTS idx_schedule_items_status
  ON schedule_items (child_id, status);


-- ============================================================
-- 2. memory_events — add favorite_at
-- ============================================================
-- is_favorite BOOLEAN DEFAULT FALSE already exists.

ALTER TABLE memory_events
  ADD COLUMN IF NOT EXISTS favorite_at TIMESTAMPTZ;

-- Composite index to speed up fetchFavoriteMoments()
CREATE INDEX IF NOT EXISTS idx_memory_events_favorite
  ON memory_events (child_id, is_favorite)
  WHERE is_favorite = TRUE;

CREATE INDEX IF NOT EXISTS idx_memory_events_child_created
  ON memory_events (child_id, created_at DESC);


-- ============================================================
-- 3. daily_summaries — new table
-- ============================================================
-- Distinct from ai_summaries (which is an older, simpler table).
-- One row per child per calendar day; generated by AI server-side.

CREATE TABLE IF NOT EXISTS daily_summaries (
  id           TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  household_id UUID        NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  child_id     TEXT        NOT NULL REFERENCES children(id)   ON DELETE CASCADE,
  summary_date DATE        NOT NULL,
  headline     TEXT        NOT NULL,
  summary      TEXT        NOT NULL,
  highlights   JSONB,
  generated_by TEXT        NOT NULL DEFAULT 'ai',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (child_id, summary_date)
);

CREATE OR REPLACE TRIGGER set_daily_summaries_updated_at
  BEFORE UPDATE ON daily_summaries
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_daily_summaries_child_date
  ON daily_summaries (child_id, summary_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_summaries_household
  ON daily_summaries (household_id);

-- RLS
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;

-- Both roles read their household's summaries
CREATE POLICY "daily_summaries:select" ON daily_summaries FOR SELECT
  USING (household_id = my_household_id());

-- Summaries are written server-side (service role bypasses RLS).
-- This policy allows parent clients to write if needed (e.g. manual entry).
CREATE POLICY "daily_summaries:insert" ON daily_summaries FOR INSERT
  WITH CHECK (household_id = my_household_id() AND my_role() = 'parent');

CREATE POLICY "daily_summaries:update" ON daily_summaries FOR UPDATE
  USING (household_id = my_household_id() AND my_role() = 'parent');

CREATE POLICY "daily_summaries:delete" ON daily_summaries FOR DELETE
  USING (household_id = my_household_id() AND my_role() = 'parent');


-- ============================================================
-- 4. sprout_notices — new table
-- ============================================================
-- AI-generated or system notices scoped to a household + child.
-- dismissed_by is a JSONB object: { "nanny": true, "parent": false }
-- A notice is fully dismissed once both roles have dismissed it
-- (or when appropriate for the notice_type).

CREATE TABLE IF NOT EXISTS sprout_notices (
  id           TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  household_id UUID        NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  child_id     TEXT        NOT NULL REFERENCES children(id)   ON DELETE CASCADE,
  notice_type  TEXT        NOT NULL,   -- 'developmental' | 'activity' | 'schedule' | 'milestone' | 'system'
  title        TEXT        NOT NULL,
  body         TEXT        NOT NULL,
  source       TEXT        NOT NULL DEFAULT 'ai',  -- 'ai' | 'system' | 'nanny' | 'parent'
  metadata     JSONB       NOT NULL DEFAULT '{}',
  dismissed_by JSONB       NOT NULL DEFAULT '{}',  -- { "nanny": true } once dismissed
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sprout_notices_child
  ON sprout_notices (child_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sprout_notices_household
  ON sprout_notices (household_id, created_at DESC);

-- RLS
ALTER TABLE sprout_notices ENABLE ROW LEVEL SECURITY;

-- Both roles read notices for their household
CREATE POLICY "sprout_notices:select" ON sprout_notices FOR SELECT
  USING (household_id = my_household_id());

-- Service role writes notices; both client roles can also create system notices
CREATE POLICY "sprout_notices:insert" ON sprout_notices FOR INSERT
  WITH CHECK (household_id = my_household_id());

-- Both roles can update dismissed_by (and only that field matters for updates)
CREATE POLICY "sprout_notices:update" ON sprout_notices FOR UPDATE
  USING (household_id = my_household_id());

-- Parents can hard-delete notices
CREATE POLICY "sprout_notices:delete" ON sprout_notices FOR DELETE
  USING (household_id = my_household_id() AND my_role() = 'parent');


-- ============================================================
-- 5. household_members — add display fields
-- ============================================================

ALTER TABLE household_members
  ADD COLUMN IF NOT EXISTS display_name TEXT,
  ADD COLUMN IF NOT EXISTS avatar_url   TEXT;

-- Index so useAuthInit can look up members by household quickly
CREATE INDEX IF NOT EXISTS idx_household_members_household
  ON household_members (household_id);
