import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

function getAdmin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

export async function POST(req: NextRequest) {
  try {
    const authToken = req.headers.get("authorization")?.replace("Bearer ", "");
    const { data: { user } } = await getAdmin().auth.getUser(authToken ?? "");
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { email, household_id, role = "caregiver" } = await req.json();
    if (!email || !household_id) {
      return NextResponse.json({ error: "Missing params" }, { status: 400 });
    }

    // Caller must be a parent in this household
    const { data: membership } = await getAdmin()
      .from("household_members")
      .select("role")
      .eq("user_id", user.id)
      .eq("household_id", household_id)
      .eq("status", "active")
      .maybeSingle();

    if (!membership || membership.role !== "parent") {
      return NextResponse.json({ error: "Only parents can invite" }, { status: 403 });
    }

    const normalised = email.trim().toLowerCase();

    // Expire any existing pending invite for this email + household
    await getAdmin()
      .from("caregiver_invites")
      .update({ status: "expired" })
      .eq("email", normalised)
      .eq("household_id", household_id)
      .eq("status", "pending");

    // Insert — token generated by the DB default encode(gen_random_bytes(32), 'hex')
    const { data: invite, error: insertErr } = await getAdmin()
      .from("caregiver_invites")
      .insert({
        household_id,
        invited_by: user.id,
        email:      normalised,
        role,
        status:     "pending",
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      })
      .select("id, token")
      .single();

    if (insertErr || !invite) {
      return NextResponse.json({ error: "Could not create invite" }, { status: 500 });
    }

    const origin = new URL(req.url).origin;
    const link   = `${origin}/invite/${invite.token}`;

    return NextResponse.json({ invite_id: invite.id, token: invite.token, link });
  } catch {
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
